# Generated by Django 5.2.5 on 2025-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='skillmodel',
            name='skills',
            field=models.ManyToManyField(to='developersInfo.developersmodel'),
        ),
    ]
