# Generated by Django 5.2.5 on 2025-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersInfo', '0002_remove_skillmodel_skills_skillmodel_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillmodel',
            old_name='skills',
            new_name='developers',
        ),
    ]
