# Generated by Django 5.2.5 on 2025-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersInfo', '0003_rename_skills_skillmodel_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='developers',
            field=models.ManyToManyField(related_name='skills', to='developersInfo.developersmodel'),
        ),
    ]
