# Generated by Django 5.2.6 on 2025-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developersmodel',
            name='username',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
