# Generated by Django 5.2.6 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developersmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developersmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
