# Generated by Django 5.2.6 on 2025-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_alter_developersmodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='desciption',
            new_name='description',
        ),
    ]
