# Generated by Django 5.2.6 on 2025-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_rename_desciption_projectmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developersmodel',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
